---
title: "Writing the data/methods/results sections"
author: "[MACS 30200](https://github.com/css-research/course/) <br /> University of Chicago"
output:
  xaringan::moon_reader:
    css: [default, metropolis, metropolis-fonts]
    lib_dir: libs
    nature:
      beforeInit: "macros.js"
      highlightLanguage: r
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(cache = TRUE, echo = FALSE, message = FALSE, warning = FALSE,
                      fig.retina = 2)

library(tidyverse)
library(tidymodels)
library(here)
library(patchwork)

set.seed(1234)
theme_set(theme_minimal(base_size = 16))
```

# Describing data

* Describe the data as it is, not as you wish it were
* Sometimes (hopefully) you find surprises
* Demonstrate, display, describe key slices of your data
* Set up data for richer theoretical or empirical analysis

---

# Where ideas come from

* Media article/report claim - "is that true?"
    * Read the day's news headlines, tweets, and posts
* New types of events/shocks
    * Great recession, natural experiments, Trump election
* **New data sources allow for new questions and/or answers**
* New methods allow for new questions and/or answers

---

# Piketty example

* Piketty (2014) identifies income inequality is increasing in developed countries
* Studies using new data sources find more nuances in this claim
    * [Sacerdote (2017)](http://www.nber.org/papers/w23292) - focus on consumption
    * [Chetty et al (2018)](http://www.equality-of-opportunity.org/assets/documents/race_paper.pdf) - [racial gaps and income inequality](https://www.nytimes.com/interactive/2018/03/19/upshot/race-class-white-and-black-men.html)

---

# Components of a data/methods section

1. Describe how to access data, where stored, who curates
1. Cite other key papers that have used this data
1. Describe how the data were collected
1. Describe key variables
1. Map the variables from the data to the concepts of your model
1. Describe the core methods employed in the study
1. Set up the data for the richer analyses you are going to do
1. Demonstrate the key result of your analysis with one visualization or table
1. Add a data appendix
1. Make your data and code accessible

---

# Critique a data section

* [Broockman, D. E., & Skovron, C. (2018). Bias in Perceptions of Public Opinion among Political Elites. *American Political Science Review*, 1-22.](https://www.cambridge.org/core/journals/american-political-science-review/article/bias-in-perceptions-of-public-opinion-among-political-elites/2EF080E04D3AAE6AC1C894F52642E706/share/1bd83a8a05b6ac177c51e7a19aee1c55f3ef4b97)

---

# Types of computational research

* Descriptive
* Identification
* Numerical solutions

---

# Descriptive papers

* New data sets
* Highlight interesting slices
* Suggestive of more rigorous analysis
* Highlight unexplained relationships, puzzles
* **You should be doing more than this in your projects**

---

# Identification papers

* $y = f(x)$
* Identify the relationship/mapping between $x$ and $y$
* Could be a question of inference or prediction
* Most academic papers are identification papers

---

# Numerical solution

* $f(x) = 0$
* Model solution requires computation
* Linked to formal/pure theory, but requires computational analysis to solve the model
* Only perhaps one or two of you are doing this

---

# Example papers

## Descriptive

* [Heathcote, J., Perri, F., & Violante, G. L. (2010). Unequal we stand: An empirical analysis of economic inequality in the United States, 1967–2006. *Review of Economic dynamics*, 13(1), 15-51.](https://www.minneapolisfed.org/research/sr/sr436.pdf)

--

## Identification

* [Mobley, L. R., Watson, L., & Brown, G. G. (2012). Geographic disparities in late-stage cancer diagnosis: multilevel factors and spatial interactions. *Health & place*, 18(5), 978-990.](https://www.sciencedirect.com/science/article/pii/S1353829212001165)

---

# Components of results section

## Identification papers

1. Give a small review of literature behind your method
1. Describe your computational model
1. Tables and figures
    * [When do use a table vs. a figure](https://www.cambridge.org/core/journals/perspectives-on-politics/article/using-graphs-instead-of-tables-in-political-science/9FD63E9EE686AF046732191EE8A68034)
    * Always use meaningful titles and text labels
1. Sensitivity/robustness analysis

---

# Critique a results section

* [Broockman, D. E., & Skovron, C. (2018). Bias in Perceptions of Public Opinion among Political Elites. *American Political Science Review*, 1-22.](https://www.cambridge.org/core/journals/american-political-science-review/article/bias-in-perceptions-of-public-opinion-among-political-elites/2EF080E04D3AAE6AC1C894F52642E706/share/1bd83a8a05b6ac177c51e7a19aee1c55f3ef4b97)

---

# Order of paper production

1. Data or theory section
1. Theory or data section
1. Computational results section
1. Conclusion
1. Introduction
1. Abstract
1. Title

* Section orders can be changed
* Sections can be expanded/consolidated depending on need

