---
title: "Homework 06: Linear Model Selection and Regularization"
date: 2019-02-12T13:30:00-06:00  # Schedule page publish date

draft: false
type: post

output:
  blogdown::html_page:
    number_sections: false

summary: "Implement methods for linear model selection, regularization, and dimension reduction."
---

\newcommand{\E}{\mathrm{E}} \newcommand{\Var}{\mathrm{Var}} \newcommand{\Cov}{\mathrm{Cov}} \newcommand{\se}{\text{se}}

# Overview

Due by 11:59pm February 18th.

# Fork the `hw06` repository

Go [here](https://github.com/css-model/hw06) to fork the repo for homework 06.

# Submission format

For each of the following questions, produce brief written answers and/or the required graphs. Your responses must be readable on GitHub (i.e. we should not have to fork your repo to view the responses). The document should be **reproducible**. This means you need to commit and push all your code, output, and written text to complete the exercises. If necessary, I should be able to clone your repository and run all the code without any errors. Recommended document formats are Jupyter Notebook (`.ipynb`) or R Markdown (`.Rmd`) rendered as `pdf_document`.^[`html_document` cannot be viewed directly on GitHub.com, and GitHub does not properly render mathematical equations in `.md` documents `r emo::ji("sad")`]

# Conceptual exercises (4 points)

## Training/test error for subset selection

a. Generate a data set with $p = 20$ features, $n = 1000$ observations, and an associated quantitative response vector generated according to the model

    $$Y = X\beta + \epsilon$$
    
    where $\beta$ has some elements that are exactly equal to zero.
    
a. Split your data set into a training set containing 100 observations and a test set containing 900 observations.
a. Perform best subset selection on the training set, and plot the training set MSE associated with the best model of each size. For which model size does the training set MSE take on its minimum value?
a. Plot the test set MSE associated with the best model of each size.
a. For which model size does the test set MSE take on its minimum value? Comment on your results.

    > If it takes on its minimum value for a model containing only an intercept or a model containing all of the features, then play around with the way that you generate the data in (a) until you create a data generating process in which the test set MSE is minimized for an intermediate model size.
a. How does the model at which the test set MSE is minimized compare to the true model used to generate the data? Comment on the coefficient sizes.
a. Create a plot displaying

    $$\sqrt{\sum_{j=1}^p (\beta_j - \hat{\beta}_j^r)^2}$$
    
    for a range of values of $r$, where $\hat{\beta}_j^r$ is the $j$th coefficient estimate for the best model containing $r$ coefficients. Comment on what you observe. How does this compare to the test MSE plot from (d)?
    
# Application exercises (6 points)

The [General Social Survey](http://gss.norc.org/) is a biannual survey of the American public.^[Conducted by NORC at the University of Chicago.]

> [The GSS gathers data on contemporary American society in order to monitor and explain trends and constants in attitudes, behaviors, and attributes. Hundreds of trends have been tracked since 1972. In addition, since the GSS adopted questions from earlier surveys, trends can be followed for up to 70 years. The GSS contains a standard core of demographic, behavioral, and attitudinal questions, plus topics of special interest. Among the topics covered are civil liberties, crime and violence, intergroup tolerance, morality, national spending priorities, psychological well-being, social mobility, and stress and traumatic events.](http://gss.norc.org/About-The-GSS)

In this problem set, you are going to predict individual feelings towards egalitarianism. Specifically, `egalit_scale` is an additive index constructed from a series of questions designed to measure how egalitarian individuals are -- that is, the extend to which they think economic opportunities should be distributed more equally in society. The variable ranges from 1 (low egalitarianism) to 35 (high egalitarianism).

`gss_*.csv` contain a selection of variables from the 2012 GSS. Documentation for the other predictors (if the variable is not clearly coded) can be viewed [here](https://gssdataexplorer.norc.org/variables/vfilter). Some data pre-processing has been done in advance for you to ease your model fitting:

1. Missing values have been imputed.
1. Nominal variables with more than two classes have been converted to dummy variables.
1. Remaining categorical variables have been converted to integer values, stripping their original labels.

Your mission is to construct a series of statistical/machine learning models to accurately predict an individual's egalitarianism using model selection and regularization methods. Use all the available predictors for each model, unless otherwise specified.

1. Fit a linear model using least squares on the training set, and report the test MSE.
1. Fit a ridge regression model on the training set, with $\lambda$ chosen by 10-fold cross-validation. Report the test MSE.
1. Fit a lasso model on the training set, with $\lambda$ chosen by 10-fold cross-validation. Report the test MSE, along with the number of non-zero coefficient estimates.
1. Fit an elastic net model on the training set, with $\alpha$ and $\lambda$ chosen by 10-fold cross-validation. That is, estimate models with $\alpha = 0, 0.1, 0.2, \ldots, 1$ using the same values for lambda across each model. Select the combination of $\alpha$ and $\lambda$ with the lowest cross-validation MSE. For that combination, report the test MSE along with the number of non-zero coefficient estimates.
1. Fit a PCR model on the training set, with $M$ chosen by 10-fold cross-validation. Only use non-binary variables as predictors for this model. Report the test error obtained, along with the value of $M$ selected by cross-validation.
1. Fit a PLS model on the training set, with $M$ chosen by 10-fold cross-validation. Only use non-binary variables as predictors for this model. Report the test error obtained, along with the value of $M$ selected by cross-validation.
1. Comment on the results obtained. How accurately can we predict an individual's egalitarianism? Is there much difference among the test errors resulting from these six approaches?

