---
title: "Selecting and Fitting a Model"
date: 2019-01-03T13:30:00  # Schedule page publish date.
draft: false
type: "talk"

output:
  blogdown::html_page:
    toc: false
    number_sections: false

# Talk start and end times.
#   End time can optionally be hidden by prefixing the line with `#`.
time_start: 2019-01-09T13:30:00
time_end: 2019-01-09T15:00:00

# Authors. Comma separated list, e.g. `["Bob Smith", "David Jones"]`.
authors: []

# Abstract and optional shortened version.
abstract: ""
abstract_short: "An overview of fitting various statistical models, the bias-variance trade-off, and selecting between different modeling strategies."

# Location of event.
location: "Room 247, Saieh Hall for Economics, Chicago, IL"

# Is this a selected talk? (true/false)
selected: false

# Tags (optional).
#   Set `tags: []` for no tags, or use the form `tags: ["A Tag", "Another Tag"]` for one or more tags.
tags: []

# Links (optional).
url_pdf: ""
url_slides: ""
url_video: ""
url_code: ""

# Does the content use math formatting?
math: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Overview

* Define statistical learning
* Distinguish between statistical and machine learning
* Assess the trade-off between prediction accuracy and model interpretability
* Define and demonstrate the bias-variance trade-off
* Define decision theory and identify generic methods for evaluating the performance of statistical models

## Before class

* ISL ch 2
* PRML ch 1
    * Ch 1.2 is a succinct review of probability theory for those needing a refresher
    * Focus most closely on ch 1.5

## Slides and class materials

* Slides

### Additional readings

* ISL ch 6.1.3
* ESL ch 7.1-7.7

## What you need to do

* [Register your GitHub username for the course](https://goo.gl/forms/vqwIztpqLb5Dhs3e2) -- all homework assignments will be in **private repositories**. Private repos can only be seen and edited by members of our [course organization](https://github.com/css-model). Once you register your GitHub account, I will invite you to join the course organization. If you don't register your account, you won't have access to any of the homework assignments.
