---
title: "Homework 01: Model Building and Model Selection/Fitting"
date: 2019-01-07T13:30:00-06:00  # Schedule page publish date

draft: false
type: post

output:
  blogdown::html_page:
    number_sections: false

summary: "Practice building theoretical models and assessing how to select optimal statistical learning algorithms."
---

$$\newcommand{\E}{\mathrm{E}} \newcommand{\Var}{\mathrm{Var}} \newcommand{\Cov}{\mathrm{Cov}}$$

# Overview

Due before class January 14th.

# Fork the `hw01` repository

Go [here](https://github.com/css-model/hw01) to fork the repo for homework 01.

# Building models (5 points)

For each of the following prompts, produce 800-1200 word written responses. Only PDF or [Markdown](https://www.markdownguide.org/) (`.md`) submissions will be graded. Using $\LaTeX$ is a great option - see the [recommended materials](https://model.uchicago.edu/faq/#latex) to get started.

## Deviant aggressive behavior

Consider four well-known and widely believed theories of socially deviant aggressive behavior (e.g. criminal behavior, revolutionary behavior, rude behavior):

* **Theory I**: Deviant aggressive behavior is learned from experience. Individuals in a society learn to do those things for which they receive rewards and to avoid those things for which they receive punishment.
* **Theory II**: Deviant aggressive behavior is a symbolic expression of hostility toward personal authority figures. When an individual is frustrated in his personal life, he becomes angry toward parents, bosses, or public officials. He will express this anger by deviant aggressive behavior.
* **Theory III**: Deviant aggressive behavior is the rational action of oppressed individuals. Social rules systematically discriminate among people. People who are most hurt by the rules are least likely to profit from conforming to them and thus do conform less.
* **Theory IV**: Deviant aggressive behavior is a social role. Individuals are socialized into the role through contact with a deviant subculture.
    
Answer the following questions:
    
1. What social policy would be appropriate to reduce deviant aggressive behavior if Theory I were correct? Theory II? Theory III? Theory IV?
1. During the past ten years, American society has been running a series of "experiments" with deviant aggressive behavior. Take any one of these experiments (e.g. #MeToo, mass shootings, political rhetoric) and discuss what we have learned about the four theories from this series of experiments.

## The need for a college education

Over the past 50+ years, the minimum education requirements set by employers have increased significantly. In particular, the proportion of jobs "requiring" a college degree has greatly increased.

a. The following explanatory model was produced by a student:

    > The reason for this is that college graduates are smarter.
    
    Using rule 1 of the [three rules of thumb](https://model.uchicago.edu/notes/build-a-model/#three-rules-of-thumb-for-model-building), try to put a sense of process into the model. What are employers looking for in the first place? Have their goals changed over time, and if so, why? Have the people seeking jobs changed in some way over time? How would this change interact with employers' wishes to produce the increased education requirement? Do not focus on specific answers to these questions. They are intended only to help build a better model
a. Using the third rule of thumb, produce another model that is a more general version of one you produced in (a).
a. Using the model from (b), make at least three interesting predictions. Use the second rule of thumb and look for natural experiments to which the model may be applied, and then say what your model predicts for those situations. Depending on how your model has evolved, you may or may not find some of these natural experiments useful:
    * Instances involving other kinds of potential employee characteristics such as age, sex, race, strength, technical skills
    * Other kinds of decisions made by employers such as product quality, where to locate new plants
    * Predicted changes in the educational system or training programs
    * Other kinds of changes in the characteristics of those seeking employment
    
    Be sure that the logical connection between your model and your predictions is clearly stated; and if you are using some facts about the world, state them explicitly.^[Treat them like assumptions -- they do not have to be documented, but they do have to be explicitly stated so that your derivation can be understood by others.]

# Selecting and fitting a model (5 points)

For each of the following questions, produce brief written answers and/or the required graphs. Your responses must be readable on GitHub (i.e. we should not have to fork your repo to view the responses). Any questions requiring code should be reproducible. Recommended document formats are $\LaTeX$ rendered as PDF, Jupyter Notebook (`.ipynb`), or R Markdown (`.Rmd`) rendered as `github_document` or `pdf_document`.

1. For each part, indicate whether we would generally expect the performance of a flexible statistical learning method to be better or worse than an inflexible method. Justify your answer.
    a. The sample size $n$ is extremely large, and the number of predictors $p$ is small.
    a. The number of predictors $p$ is extremely large, and the number of observations $n$ is small.
    a. The relationship between the predictors and response is highly non-linear.
    a. The variance of the error terms $\sigma^2 = \Var(\epsilon)$ is extremely high.
1. Bias-variance decomposition
    a. Generate a graph of typical (squared) bias, variance, training error, test error, and Bayes (irreducible) error curves, on a single plot, as we go from less flexible statistical learning methods towards more flexible approaches. The $x$-axis should represent the amount of flexibility in the method, and the $y$-axis should represent the values for each curve. There should be five curves. Make sure to label each one.
    a. Explain why each of the five curves has the shape displayed in part (a).
1. For classification problems, the test error rate is minimized by a simple classifier that assigns each observation to the most likely class given its predictor values:

    $$\Pr(Y = j | X = x_0)$$
    
    where $x_0$ is the test observation and each possible class is represented by $J$. This is a **conditional probability** that $Y = j$, given the observed predictor vector $x_0$. This classifier is known as the **Bayes classifier**. If the response variable is binary (i.e. two classes), the Bayes classifier corresponds to predicting class one if $\Pr(Y = 1 | X = x_0) > 0.5$, and class two otherwise.
    
    Figure 2.13 in [ISL] illustrates a simulated example defining the decision boundary for a hypothetical data set. Produce a graph illustrating this concept. Specifically, implement the following elements in your program:
    
    a. Set your random number generator seed.
    a. Simulate a dataset of $N = 200$ with $X_1, X_2$ where $X_1, X_2$ are random uniform variables between $[0,1]$.
    a. Calculate $Y = X_1 + X_1^2 + X_2 + X_2^2 + \epsilon$, where $\epsilon \sim N(\mu = 0, \theta^2 = 0.25)$.
    a. $Y$ is defined in terms of the log-odds of success on the domain $[-\infty, +\infty]$. Calculate the probability of success bounded between $[0,1]$.
    a. Plot each of the data points on a graph and use color to indicate if the observation was a success or a failure.
    a. Overlay the plot with Bayes decision boundary, calculated using $X_1, X_2$.
    a. Give your plot a meaningful title and axis labels.
    a. The colored background grid is optional.
